# Generated by Django 2.0.5 on 2019-03-11 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_auto_20190311_1833'),
        ('Game', '0002_auto_20190311_1703'),
    ]

    operations = [
    ]
